# Site settings
title: From Here On Out
header-img: img/home-bg.png
email: mjboroski@gmail.com
copyright_name: mjboroski
description: > # this means to ignore newlines until "baseurl:"
  Thoughts, musings, and other consumable information.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: mjboroski
github_username:  mjboroski
learn_profile: mjboroski
email_username: mjboroski@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
